#!/bin/sh
### BEGIN INIT INFO
# Provides: asteriskcallhistory
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Should-Start: $network
# Should-Stop: $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Multi-user daemonized version of asteriskcallhistory.
# Description: Starts the asteriskcallhistory daemon for all registered users.
### END INIT INFO

NAME="asteriskcallhistory"
PIDFILE='/var/run/asteriskcallhistory/asteriskcallhistory.pid'
DAEMON='/usr/bin/python /opt/Asterisk-Call-History/flaskr.py'
CONFIG='$PIDFILE'
DAEMON_UID='root'
DAEMON_GID='root'

case "$1" in
    start)
        echo "Starting $NAME"
        mkdir /var/run/asteriskcallhistory 2> /dev/null
        chown $DAEMON_UID:$DAEMON_UID /var/run/asteriskcallhistory
        start-stop-daemon --pidfile $PIDFILE --start --background -c $DAEMON_UID -x $DAEMON --chuid $DAEMON_UID:$DAEMON_GID -- $PIDFILE
        ;;
    stop)
        echo "Stopping $NAME"
        start-stop-daemon --pidfile $PIDFILE --stop -x $DAEMON
        rm -r /var/run/asteriskcallhistory 2> /dev/null
        ;;
    status)
        dbpid=`cat $PIDFILE`
        if [ -z "$dbpid" ]; then
          echo "Network Scanner not running."
        else
          echo "Network Scanner running (pid $dbpid)"
        fi
        ;;
    *)
        echo "Usage: /etc/init.d/asteriskcallhistory {start|stop|status}"
        exit 1
    esac
exit 0

